### ISSUE TITLE
deleted .lib-files causing issues building the project

### ISSUE THREAD

**Issue by fortiZde** [changeofpace/Overwatch-Dump-Fix#5]
Hi changeofpace,

I just want to ask whether I missed something. I checked the project out and try to build it. I got errors like:

https://github.com/changeofpace/Overwatch-Dump-Fix/commit/32f01c86eaf7fc7d66b8d13950a5e3157aab8a53
You removed the .lib files from the pluginsdk folder.

> LINK : fatal error LNK1181: cannot open input file pluginsdk\DeviceNameResolver\DeviceNameResolver_x64.lib'

I checked to older one out and take the lib-files from there. Maybe it wan't intended to remove them? :)
Thanks for your work.

**Comment by changeofpace** [comment]
Hey, thanks for opening an issue for this. The repository was in an unbuildable state.

I think the project directory name change in 32f01c86eaf7fc7d66b8d13950a5e3157aab8a53 caused the gitignore rules to be (re)applied to every file in the renamed directory. The lib files were removed because of the `*.lib` pattern. This wasn't an issue before because the lib files were pushed before the `*.lib` rule was added to the gitignore file.

I updated the gitignore file and added the lib files in 64b1aa14b6afc4246f0feed1db380025a36ccd62.
